"""ajout date_naissance et adresse eleve

Revision ID: 14b300b16740
Revises: 6c8899693880
Create Date: 2026-07-06 21:05:37.278588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b300b16740'
down_revision = '6c8899693880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_naissance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('adresse', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleves', schema=None) as batch_op:
        batch_op.drop_column('adresse')
        batch_op.drop_column('date_naissance')

    # ### end Alembic commands ###
