"""Fondations refonte : nouveaux modeles et colonnes additives

Revision ID: 6c8899693880
Revises: a2e0de11a070
Create Date: 2026-07-05 20:43:53.764256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8899693880'
down_revision = 'a2e0de11a070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annees_scolaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trimestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['annee_id'], ['annees_scolaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('lien', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('intitule', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('trimestre_id', sa.Integer(), nullable=True),
    sa.Column('saisi_par_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trimestre_id'], ['trimestres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('saisi_par_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('heure_arrivee', sa.Time(), nullable=True),
    sa.Column('justifie', sa.Boolean(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('saisi_par_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eleve_id', 'date', name='uq_presence_eleve_date')
    )
    with op.batch_alter_table('incidents_majeurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matiere_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_incidents_majeurs_matiere_id', 'matieres', ['matiere_id'], ['id'])

    with op.batch_alter_table('infractions_mineures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matiere_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_infractions_mineures_matiere_id', 'matieres', ['matiere_id'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('controle_id', sa.Integer(), nullable=True))
        batch_op.alter_column('matiere_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('trimestre',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.create_foreign_key('fk_notes_controle_id', 'controles', ['controle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notes_controle_id', type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('trimestre',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('matiere_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('controle_id')

    with op.batch_alter_table('infractions_mineures', schema=None) as batch_op:
        batch_op.drop_constraint('fk_infractions_mineures_matiere_id', type_='foreignkey')
        batch_op.drop_column('matiere_id')

    with op.batch_alter_table('incidents_majeurs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incidents_majeurs_matiere_id', type_='foreignkey')
        batch_op.drop_column('matiere_id')

    op.drop_table('presences')
    op.drop_table('notices')
    op.drop_table('controles')
    op.drop_table('contacts_parents')
    op.drop_table('trimestres')
    op.drop_table('annees_scolaires')
    # ### end Alembic commands ###
