"""initial schema

Revision ID: a2e0de11a070
Revises: 
Create Date: 2026-07-05 18:20:24.989275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e0de11a070'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles_discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('date_cloture', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_infractions_mineures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('points_deduits', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('affectations_prof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professeur_id', 'matiere_id', 'classe_id', name='uq_affectation')
    )
    op.create_table('eleves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('points_vie_scolaire', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapports_generes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('fichier_pdf', sa.String(length=255), nullable=True),
    sa.Column('fichier_excel', sa.String(length=255), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles_discipline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('saisi_par_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents_majeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('gravite', sa.String(length=20), nullable=False),
    sa.Column('sanction', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('saisi_par_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infractions_mineures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('type_infraction_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('saisi_par_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles_discipline.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_infraction_id'], ['types_infractions_mineures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('trimestre', sa.String(length=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('saisi_par_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['saisi_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots_points_eleve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('points_finaux', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles_discipline.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots_points_eleve')
    op.drop_table('notes')
    op.drop_table('infractions_mineures')
    op.drop_table('incidents_majeurs')
    op.drop_table('absences')
    op.drop_table('rapports_generes')
    op.drop_table('eleves')
    op.drop_table('affectations_prof')
    op.drop_table('users')
    op.drop_table('types_infractions_mineures')
    op.drop_table('matieres')
    op.drop_table('cycles_discipline')
    op.drop_table('classes')
    # ### end Alembic commands ###
